name: Release Binaries

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to release'
        required: true
        type: string

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            name: linux-amd64
          - goos: linux
            goarch: arm64
            name: linux-arm64
          - goos: darwin
            goarch: amd64
            name: darwin-amd64
          - goos: darwin
            goarch: arm64
            name: darwin-arm64
          - goos: windows
            goarch: amd64
            name: windows-amd64
            ext: .exe
          - goos: windows
            goarch: arm64
            name: windows-arm64
            ext: .exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Get version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            # Auto-generate version for main branch pushes
            BUILD_DATE=$(date +%Y%m%d)
            BUILD_TIME=$(date +%H%M)
            SHORT_SHA=${GITHUB_SHA::7}
            echo "version=dev-${BUILD_DATE}.${BUILD_TIME}-${SHORT_SHA}" >> $GITHUB_OUTPUT
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          # Create build directory
          mkdir -p dist
          
          # Set binary name
          BINARY_NAME="cycletls-proxy${{ matrix.ext }}"
          
          # Set build time
          BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          
          # Build the binary
          go build -ldflags "-w -s -X main.version=${{ steps.version.outputs.version }} -X main.buildTime=$BUILD_TIME -X main.gitCommit=${GITHUB_SHA::8}" -o dist/${BINARY_NAME} ./cmd/proxy
          
          # Verify binary was created
          ls -la dist/
          file dist/${BINARY_NAME}

      - name: Create versioned executable and archive
        run: |
          cd dist
          BINARY_NAME="cycletls-proxy${{ matrix.ext }}"
          VERSION_NAME="cycletls-proxy-${{ steps.version.outputs.version }}-${{ matrix.name }}${{ matrix.ext }}"
          ARCHIVE_NAME="cycletls-proxy-${{ steps.version.outputs.version }}-${{ matrix.name }}"
          
          # Create a copy with versioned name for direct download
          cp "${BINARY_NAME}" "${VERSION_NAME}"
          
          # Create archive
          if [[ "${{ matrix.goos }}" == "windows" ]]; then
            # Create zip for Windows
            zip -9 "${ARCHIVE_NAME}.zip" "${BINARY_NAME}"
            echo "ARCHIVE_FILE=${ARCHIVE_NAME}.zip" >> $GITHUB_ENV
          else
            # Create tar.gz for Unix-like systems
            tar -czf "${ARCHIVE_NAME}.tar.gz" "${BINARY_NAME}"
            echo "ARCHIVE_FILE=${ARCHIVE_NAME}.tar.gz" >> $GITHUB_ENV
          fi
          
          echo "VERSION_BINARY=${VERSION_NAME}" >> $GITHUB_ENV

      - name: Generate checksums
        run: |
          cd dist
          # Checksum for archive
          sha256sum "${ARCHIVE_FILE}" > "${ARCHIVE_FILE}.sha256"
          # Checksum for direct executable
          sha256sum "${VERSION_BINARY}" > "${VERSION_BINARY}.sha256"
          
          echo "Archive checksum:"
          cat "${ARCHIVE_FILE}.sha256"
          echo "Direct executable checksum:"
          cat "${VERSION_BINARY}.sha256"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cycletls-proxy-${{ matrix.name }}
          path: |
            dist/${{ env.ARCHIVE_FILE }}
            dist/${{ env.ARCHIVE_FILE }}.sha256
            dist/${{ env.VERSION_BINARY }}
            dist/${{ env.VERSION_BINARY }}.sha256
          retention-days: 30

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            # Auto-generate version for main branch pushes
            BUILD_DATE=$(date +%Y%m%d)
            BUILD_TIME=$(date +%H%M)
            SHORT_SHA=${GITHUB_SHA::7}
            echo "version=dev-${BUILD_DATE}.${BUILD_TIME}-${SHORT_SHA}" >> $GITHUB_OUTPUT
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          
          # Copy all archives and checksums
          find dist -name "*.tar.gz" -o -name "*.zip" -o -name "*.sha256" | xargs -I {} cp {} release-assets/
          
          # Copy direct executables (but not the original build artifacts)
          find dist -name "cycletls-proxy-*" -type f ! -name "*.tar.gz" ! -name "*.zip" ! -name "*.sha256" | xargs -I {} cp {} release-assets/
          
          echo "Release assets:"
          ls -la release-assets/
          
          echo ""
          echo "Direct executables available:"
          ls -la release-assets/ | grep -E "cycletls-proxy-.*-(linux|darwin|windows)" | grep -v ".tar.gz\|.zip\|.sha256" || echo "None found"
          
          echo ""
          echo "Archives available:"
          ls -la release-assets/ | grep -E "\.(tar\.gz|zip)$" || echo "None found"

      - name: Generate release notes
        id: release_notes
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          
          # Create release notes
          cat > release_notes.md << EOF
          # CycleTLS-Proxy ${VERSION}
          
          ## What's New
          
          This release includes the following improvements and updates:
          
          - Latest CycleTLS integration with enhanced TLS fingerprinting
          - Performance optimizations and bug fixes
          - Multi-platform binary support (Linux, macOS, Windows)
          - Advanced TLS configuration options
          
          ## Installation
          
          ### Quick Download (Direct Executables)
          
          For immediate use, download the executable directly:
          
          - **Linux AMD64**: \`cycletls-proxy-${VERSION}-linux-amd64\`
          - **Linux ARM64**: \`cycletls-proxy-${VERSION}-linux-arm64\` 
          - **macOS Intel**: \`cycletls-proxy-${VERSION}-darwin-amd64\`
          - **macOS Apple Silicon**: \`cycletls-proxy-${VERSION}-darwin-arm64\`
          - **Windows AMD64**: \`cycletls-proxy-${VERSION}-windows-amd64.exe\`
          - **Windows ARM64**: \`cycletls-proxy-${VERSION}-windows-arm64.exe\`
          
          After download, make executable (Linux/macOS): \`chmod +x cycletls-proxy-${VERSION}-*\`
          
          ### Archive Downloads (Traditional)
          
          If you prefer traditional archives:
          
          - **Linux/macOS**: \`cycletls-proxy-${VERSION}-{platform}-{arch}.tar.gz\`
          - **Windows**: \`cycletls-proxy-${VERSION}-windows-{arch}.zip\`
          
          ## Verification
          
          All release assets include SHA256 checksums for verification:
          
          \`\`\`bash
          # Verify checksum (Linux/macOS)
          sha256sum -c cycletls-proxy-${VERSION}-linux-amd64.tar.gz.sha256
          
          # Verify checksum (Windows PowerShell)
          Get-FileHash cycletls-proxy-${VERSION}-windows-amd64.zip -Algorithm SHA256
          \`\`\`
          
          ## Usage
          
          After extracting the binary, run:
          
          \`\`\`bash
          ./cycletls-proxy
          \`\`\`
          
          The proxy will start on port 8080 by default. See the [documentation](https://github.com/Danny-Dasilva/CycleTLS-Proxy) for configuration options.
          
          ---
          
          **Full Changelog**: https://github.com/Danny-Dasilva/CycleTLS-Proxy/compare/${{ github.event.before }}...${{ steps.version.outputs.version }}
          EOF

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.is_release == 'true' && format('Release {0}', steps.version.outputs.version) || format('Development Build {0}', steps.version.outputs.version) }}
          body_path: release_notes.md
          files: release-assets/*
          draft: false
          prerelease: ${{ steps.version.outputs.is_release == 'false' || contains(steps.version.outputs.version, 'beta') || contains(steps.version.outputs.version, 'alpha') || contains(steps.version.outputs.version, 'rc') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update latest release info
        if: "!contains(steps.version.outputs.version, 'beta') && !contains(steps.version.outputs.version, 'alpha') && !contains(steps.version.outputs.version, 'rc')"
        run: |
          echo "Latest stable release: ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Binary downloads available in release assets" >> $GITHUB_STEP_SUMMARY